/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Airplane;

public class App {
  
  public static void main(String[] args) {
    
    AirPlane air = new AirPlane();
    air.airplaneInfo();
    air.airPlaneTotalCount();
  }
}
